### PR TITLE
Feature#19 passenger screen

### PR DESCRIPTION
**Pull request by daniel-yocupicio**
# Description
The Passenger screen was created, this view is used to enter the number of passengers that will be reserved.

 
  ## Screenshots 
image

### CODE REVIEW

**Review by FranciscoSenestrari — APPROVED** [review]
Good job

**Review by GerardoTovar — APPROVED** [review]
the code was clean

**Review by FranciscoSenestrari — APPROVED** [review]
nice

**Review by valen-ruggieri — DISMISSED** [review]
good code and achieves its correct operation

**Review by GerardoTovar — APPROVED** [review]

**Review by LizyMiGo — APPROVED** [review]
Good

**Review by ShamuXX — APPROVED** [review]

**Pull request merged**
